name: BlazeCI Test Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # allows manual triggering from GitHub UI

jobs:
  test:
    name: Run Python Tests on BlazeCI
    runs-on: blazeci-small   # 👈 your custom runner label
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # - name: Run tests
      #   run: |
      #     pytest --maxfail=1 --disable-warnings -q
